package com.ssic.game.common.mapper;

import com.ssic.game.common.pojo.FieldRole;
import com.ssic.game.common.pojo.FieldRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FieldRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int countByExample(FieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int deleteByExample(FieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int insert(FieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int insertSelective(FieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    List<FieldRole> selectByExample(FieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    FieldRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") FieldRole record, @Param("example") FieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByExample(@Param("record") FieldRole record, @Param("example") FieldRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByPrimaryKeySelective(FieldRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_field_role
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByPrimaryKey(FieldRole record);
}