package com.ssic.game.common.mapper;

import com.ssic.game.common.pojo.ImsUsers;
import com.ssic.game.common.pojo.ImsUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImsUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int countByExample(ImsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int deleteByExample(ImsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int insert(ImsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int insertSelective(ImsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    List<ImsUsers> selectByExample(ImsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    ImsUsers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") ImsUsers record, @Param("example") ImsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int updateByExample(@Param("record") ImsUsers record, @Param("example") ImsUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int updateByPrimaryKeySelective(ImsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_users
     *
     * @mbggenerated Mon Nov 16 13:40:12 CST 2015
     */
    int updateByPrimaryKey(ImsUsers record);
}