package com.ssic.game.common.mapper;

import com.ssic.game.common.pojo.ProjectRole;
import com.ssic.game.common.pojo.ProjectRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int countByExample(ProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int deleteByExample(ProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int insert(ProjectRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int insertSelective(ProjectRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    List<ProjectRole> selectByExample(ProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    ProjectRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProjectRole record, @Param("example") ProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int updateByExample(@Param("record") ProjectRole record, @Param("example") ProjectRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int updateByPrimaryKeySelective(ProjectRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_project_role
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    int updateByPrimaryKey(ProjectRole record);
}