package com.ssic.game.common.mapper;

import com.ssic.game.common.pojo.RoleMenu;
import com.ssic.game.common.pojo.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    RoleMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_role_menu
     *
     * @mbggenerated Tue Aug 11 11:41:53 CST 2015
     */
    int updateByPrimaryKey(RoleMenu record);
}