package com.ssic.game.common.mapper;

import com.ssic.game.common.pojo.SysLogs;
import com.ssic.game.common.pojo.SysLogsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int countByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int deleteByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int insert(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int insertSelective(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    List<SysLogs> selectByExample(SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    SysLogs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysLogs record, @Param("example") SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByExample(@Param("record") SysLogs record, @Param("example") SysLogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByPrimaryKeySelective(SysLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ims_sys_logs
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    int updateByPrimaryKey(SysLogs record);
}