package com.ssic.catering.base.pojo;

import java.util.Date;

public class ConfigScoreValveConf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.cafetorium_id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private String cafetoriumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.level
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.valve_count
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Integer valveCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.valve_percent
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Float valvePercent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.create_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.last_update_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_config_score_valve_conf.stat
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.id
     *
     * @return the value of t_ctr_config_score_valve_conf.id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.id
     *
     * @param id the value for t_ctr_config_score_valve_conf.id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.cafetorium_id
     *
     * @return the value of t_ctr_config_score_valve_conf.cafetorium_id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public String getCafetoriumId() {
        return cafetoriumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.cafetorium_id
     *
     * @param cafetoriumId the value for t_ctr_config_score_valve_conf.cafetorium_id
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setCafetoriumId(String cafetoriumId) {
        this.cafetoriumId = cafetoriumId == null ? null : cafetoriumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.level
     *
     * @return the value of t_ctr_config_score_valve_conf.level
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.level
     *
     * @param level the value for t_ctr_config_score_valve_conf.level
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.valve_count
     *
     * @return the value of t_ctr_config_score_valve_conf.valve_count
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Integer getValveCount() {
        return valveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.valve_count
     *
     * @param valveCount the value for t_ctr_config_score_valve_conf.valve_count
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setValveCount(Integer valveCount) {
        this.valveCount = valveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.valve_percent
     *
     * @return the value of t_ctr_config_score_valve_conf.valve_percent
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Float getValvePercent() {
        return valvePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.valve_percent
     *
     * @param valvePercent the value for t_ctr_config_score_valve_conf.valve_percent
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setValvePercent(Float valvePercent) {
        this.valvePercent = valvePercent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.create_time
     *
     * @return the value of t_ctr_config_score_valve_conf.create_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.create_time
     *
     * @param createTime the value for t_ctr_config_score_valve_conf.create_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.last_update_time
     *
     * @return the value of t_ctr_config_score_valve_conf.last_update_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_config_score_valve_conf.last_update_time
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_config_score_valve_conf.stat
     *
     * @return the value of t_ctr_config_score_valve_conf.stat
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_config_score_valve_conf.stat
     *
     * @param stat the value for t_ctr_config_score_valve_conf.stat
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}