package com.ssic.catering.base.pojo;

import java.util.Date;

public class CorkContractor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.company_name
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.cafetorium_id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private String cafetoriumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.stat
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.last_update_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_fork_contractor.create_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.id
     *
     * @return the value of t_ctr_fork_contractor.id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.id
     *
     * @param id the value for t_ctr_fork_contractor.id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.company_name
     *
     * @return the value of t_ctr_fork_contractor.company_name
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.company_name
     *
     * @param companyName the value for t_ctr_fork_contractor.company_name
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.cafetorium_id
     *
     * @return the value of t_ctr_fork_contractor.cafetorium_id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public String getCafetoriumId() {
        return cafetoriumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.cafetorium_id
     *
     * @param cafetoriumId the value for t_ctr_fork_contractor.cafetorium_id
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setCafetoriumId(String cafetoriumId) {
        this.cafetoriumId = cafetoriumId == null ? null : cafetoriumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.stat
     *
     * @return the value of t_ctr_fork_contractor.stat
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.stat
     *
     * @param stat the value for t_ctr_fork_contractor.stat
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.last_update_time
     *
     * @return the value of t_ctr_fork_contractor.last_update_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_fork_contractor.last_update_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_fork_contractor.create_time
     *
     * @return the value of t_ctr_fork_contractor.create_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_fork_contractor.create_time
     *
     * @param createTime the value for t_ctr_fork_contractor.create_time
     *
     * @mbggenerated Thu Aug 06 16:36:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}