package com.ssic.catering.base.pojo;

import java.util.Date;

public class GroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.group_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.group_name
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String groupInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.group_head
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String groupHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.create_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.createUserID
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.stat
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.group_user_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String groupUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.parent_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_group_info.proj_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    private String projId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.id
     *
     * @return the value of t_ctr_group_info.id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.id
     *
     * @param id the value for t_ctr_group_info.id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.group_id
     *
     * @return the value of t_ctr_group_info.group_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.group_id
     *
     * @param groupId the value for t_ctr_group_info.group_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.group_name
     *
     * @return the value of t_ctr_group_info.group_name
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.group_name
     *
     * @param groupName the value for t_ctr_group_info.group_name
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.group_info
     *
     * @return the value of t_ctr_group_info.group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getGroupInfo() {
        return groupInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.group_info
     *
     * @param groupInfo the value for t_ctr_group_info.group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setGroupInfo(String groupInfo) {
        this.groupInfo = groupInfo == null ? null : groupInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.group_head
     *
     * @return the value of t_ctr_group_info.group_head
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getGroupHead() {
        return groupHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.group_head
     *
     * @param groupHead the value for t_ctr_group_info.group_head
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setGroupHead(String groupHead) {
        this.groupHead = groupHead == null ? null : groupHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.create_time
     *
     * @return the value of t_ctr_group_info.create_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.create_time
     *
     * @param createTime the value for t_ctr_group_info.create_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.last_update_time
     *
     * @return the value of t_ctr_group_info.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_group_info.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.createUserID
     *
     * @return the value of t_ctr_group_info.createUserID
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.createUserID
     *
     * @param createuserid the value for t_ctr_group_info.createUserID
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.stat
     *
     * @return the value of t_ctr_group_info.stat
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.stat
     *
     * @param stat the value for t_ctr_group_info.stat
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.group_user_id
     *
     * @return the value of t_ctr_group_info.group_user_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getGroupUserId() {
        return groupUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.group_user_id
     *
     * @param groupUserId the value for t_ctr_group_info.group_user_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setGroupUserId(String groupUserId) {
        this.groupUserId = groupUserId == null ? null : groupUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.parent_id
     *
     * @return the value of t_ctr_group_info.parent_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.parent_id
     *
     * @param parentId the value for t_ctr_group_info.parent_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_group_info.proj_id
     *
     * @return the value of t_ctr_group_info.proj_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_group_info.proj_id
     *
     * @param projId the value for t_ctr_group_info.proj_id
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }
}