package com.ssic.catering.base.pojo;

import java.util.Date;

public class MeetingAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.name
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.stat
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.last_update_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.create_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.province
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.city
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.address
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.large_area
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String largeArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_meeting_address.proj_id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    private String projId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.id
     *
     * @return the value of t_ctr_meeting_address.id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.id
     *
     * @param id the value for t_ctr_meeting_address.id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.name
     *
     * @return the value of t_ctr_meeting_address.name
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.name
     *
     * @param name the value for t_ctr_meeting_address.name
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.stat
     *
     * @return the value of t_ctr_meeting_address.stat
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.stat
     *
     * @param stat the value for t_ctr_meeting_address.stat
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.last_update_time
     *
     * @return the value of t_ctr_meeting_address.last_update_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_meeting_address.last_update_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.create_time
     *
     * @return the value of t_ctr_meeting_address.create_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.create_time
     *
     * @param createTime the value for t_ctr_meeting_address.create_time
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.province
     *
     * @return the value of t_ctr_meeting_address.province
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.province
     *
     * @param province the value for t_ctr_meeting_address.province
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.city
     *
     * @return the value of t_ctr_meeting_address.city
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.city
     *
     * @param city the value for t_ctr_meeting_address.city
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.address
     *
     * @return the value of t_ctr_meeting_address.address
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.address
     *
     * @param address the value for t_ctr_meeting_address.address
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.large_area
     *
     * @return the value of t_ctr_meeting_address.large_area
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getLargeArea() {
        return largeArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.large_area
     *
     * @param largeArea the value for t_ctr_meeting_address.large_area
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setLargeArea(String largeArea) {
        this.largeArea = largeArea == null ? null : largeArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_meeting_address.proj_id
     *
     * @return the value of t_ctr_meeting_address.proj_id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_meeting_address.proj_id
     *
     * @param projId the value for t_ctr_meeting_address.proj_id
     *
     * @mbggenerated Fri Oct 23 11:28:11 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }
}