package com.ssic.shop.manage.mapper;

import com.ssic.shop.manage.pojo.CarteUser;
import com.ssic.shop.manage.pojo.CarteUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarteUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int countByExample(CarteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int deleteByExample(CarteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int insert(CarteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int insertSelective(CarteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    List<CarteUser> selectByExample(CarteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    CarteUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") CarteUser record, @Param("example") CarteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int updateByExample(@Param("record") CarteUser record, @Param("example") CarteUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int updateByPrimaryKeySelective(CarteUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_user
     *
     * @mbggenerated Tue Oct 20 11:41:36 CST 2015
     */
    int updateByPrimaryKey(CarteUser record);
}