package com.ssic.shop.manage.mapper;

import com.ssic.shop.manage.pojo.DinnerSeries;
import com.ssic.shop.manage.pojo.DinnerSeriesExample;
import com.ssic.shop.manage.pojo.DinnerSeriesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DinnerSeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int countByExample(DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByExample(DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insert(DinnerSeriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insertSelective(DinnerSeriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    List<DinnerSeriesWithBLOBs> selectByExampleWithBLOBs(DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    List<DinnerSeries> selectByExample(DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    DinnerSeriesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") DinnerSeriesWithBLOBs record, @Param("example") DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") DinnerSeriesWithBLOBs record, @Param("example") DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExample(@Param("record") DinnerSeries record, @Param("example") DinnerSeriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKeySelective(DinnerSeriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(DinnerSeriesWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_dinner_series
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKey(DinnerSeries record);
}