package com.ssic.shop.manage.mapper;

import com.ssic.shop.manage.pojo.IntegralExchangeType;
import com.ssic.shop.manage.pojo.IntegralExchangeTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntegralExchangeTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int countByExample(IntegralExchangeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByExample(IntegralExchangeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insert(IntegralExchangeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insertSelective(IntegralExchangeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    List<IntegralExchangeType> selectByExample(IntegralExchangeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    IntegralExchangeType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") IntegralExchangeType record, @Param("example") IntegralExchangeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExample(@Param("record") IntegralExchangeType record, @Param("example") IntegralExchangeTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKeySelective(IntegralExchangeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_integral_exchange_type
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKey(IntegralExchangeType record);
}