package com.ssic.shop.manage.mapper;

import com.ssic.shop.manage.pojo.LuckyDrawHistory;
import com.ssic.shop.manage.pojo.LuckyDrawHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyDrawHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int countByExample(LuckyDrawHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByExample(LuckyDrawHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insert(LuckyDrawHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int insertSelective(LuckyDrawHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    List<LuckyDrawHistory> selectByExample(LuckyDrawHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    LuckyDrawHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") LuckyDrawHistory record, @Param("example") LuckyDrawHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByExample(@Param("record") LuckyDrawHistory record, @Param("example") LuckyDrawHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKeySelective(LuckyDrawHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_lucky_draw_history
     *
     * @mbggenerated Tue Oct 20 14:43:00 CST 2015
     */
    int updateByPrimaryKey(LuckyDrawHistory record);
}