package com.ssic.shop.manage.mapper;

import com.ssic.shop.manage.pojo.WeixnUserCafetorium;
import com.ssic.shop.manage.pojo.WeixnUserCafetoriumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeixnUserCafetoriumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int countByExample(WeixnUserCafetoriumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int deleteByExample(WeixnUserCafetoriumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int insert(WeixnUserCafetorium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int insertSelective(WeixnUserCafetorium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    List<WeixnUserCafetorium> selectByExample(WeixnUserCafetoriumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    WeixnUserCafetorium selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") WeixnUserCafetorium record, @Param("example") WeixnUserCafetoriumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int updateByExample(@Param("record") WeixnUserCafetorium record, @Param("example") WeixnUserCafetoriumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int updateByPrimaryKeySelective(WeixnUserCafetorium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_weixn_user_cafetorium
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    int updateByPrimaryKey(WeixnUserCafetorium record);
}