package com.ssic.shop.manage.pojo;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.goods_name
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.sales_price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Double salesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.detail_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String detailIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.turn_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String turnIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.introduce
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.is_turn
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer isTurn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.count_limit
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer countLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.percent
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.goods_type_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String goodsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.cafetorium_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String cafetoriumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.goods_stocks
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer goodsStocks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.create_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.last_update_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.stat
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.is_stick
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private Integer isStick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.importdomestic
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String importdomestic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.placeorigin
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String placeorigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.distributionmode
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String distributionmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.unitsize
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String unitsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.productiondate
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String productiondate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.shelflife
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String shelflife;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.purchase
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String purchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_goods.detailsimgsrc
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    private String detailsimgsrc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.id
     *
     * @return the value of t_ctr_goods.id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.id
     *
     * @param id the value for t_ctr_goods.id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.goods_name
     *
     * @return the value of t_ctr_goods.goods_name
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.goods_name
     *
     * @param goodsName the value for t_ctr_goods.goods_name
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.price
     *
     * @return the value of t_ctr_goods.price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.price
     *
     * @param price the value for t_ctr_goods.price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.sales_price
     *
     * @return the value of t_ctr_goods.sales_price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Double getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.sales_price
     *
     * @param salesPrice the value for t_ctr_goods.sales_price
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setSalesPrice(Double salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.icon
     *
     * @return the value of t_ctr_goods.icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.icon
     *
     * @param icon the value for t_ctr_goods.icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.detail_icon
     *
     * @return the value of t_ctr_goods.detail_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getDetailIcon() {
        return detailIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.detail_icon
     *
     * @param detailIcon the value for t_ctr_goods.detail_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setDetailIcon(String detailIcon) {
        this.detailIcon = detailIcon == null ? null : detailIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.turn_icon
     *
     * @return the value of t_ctr_goods.turn_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getTurnIcon() {
        return turnIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.turn_icon
     *
     * @param turnIcon the value for t_ctr_goods.turn_icon
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setTurnIcon(String turnIcon) {
        this.turnIcon = turnIcon == null ? null : turnIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.introduce
     *
     * @return the value of t_ctr_goods.introduce
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.introduce
     *
     * @param introduce the value for t_ctr_goods.introduce
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.is_turn
     *
     * @return the value of t_ctr_goods.is_turn
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getIsTurn() {
        return isTurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.is_turn
     *
     * @param isTurn the value for t_ctr_goods.is_turn
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setIsTurn(Integer isTurn) {
        this.isTurn = isTurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.count_limit
     *
     * @return the value of t_ctr_goods.count_limit
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getCountLimit() {
        return countLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.count_limit
     *
     * @param countLimit the value for t_ctr_goods.count_limit
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setCountLimit(Integer countLimit) {
        this.countLimit = countLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.percent
     *
     * @return the value of t_ctr_goods.percent
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.percent
     *
     * @param percent the value for t_ctr_goods.percent
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.goods_type_id
     *
     * @return the value of t_ctr_goods.goods_type_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getGoodsTypeId() {
        return goodsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.goods_type_id
     *
     * @param goodsTypeId the value for t_ctr_goods.goods_type_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setGoodsTypeId(String goodsTypeId) {
        this.goodsTypeId = goodsTypeId == null ? null : goodsTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.cafetorium_id
     *
     * @return the value of t_ctr_goods.cafetorium_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getCafetoriumId() {
        return cafetoriumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.cafetorium_id
     *
     * @param cafetoriumId the value for t_ctr_goods.cafetorium_id
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setCafetoriumId(String cafetoriumId) {
        this.cafetoriumId = cafetoriumId == null ? null : cafetoriumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.goods_stocks
     *
     * @return the value of t_ctr_goods.goods_stocks
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getGoodsStocks() {
        return goodsStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.goods_stocks
     *
     * @param goodsStocks the value for t_ctr_goods.goods_stocks
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setGoodsStocks(Integer goodsStocks) {
        this.goodsStocks = goodsStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.create_time
     *
     * @return the value of t_ctr_goods.create_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.create_time
     *
     * @param createTime the value for t_ctr_goods.create_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.last_update_time
     *
     * @return the value of t_ctr_goods.last_update_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_goods.last_update_time
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.stat
     *
     * @return the value of t_ctr_goods.stat
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.stat
     *
     * @param stat the value for t_ctr_goods.stat
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.is_stick
     *
     * @return the value of t_ctr_goods.is_stick
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public Integer getIsStick() {
        return isStick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.is_stick
     *
     * @param isStick the value for t_ctr_goods.is_stick
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setIsStick(Integer isStick) {
        this.isStick = isStick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.importdomestic
     *
     * @return the value of t_ctr_goods.importdomestic
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getImportdomestic() {
        return importdomestic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.importdomestic
     *
     * @param importdomestic the value for t_ctr_goods.importdomestic
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setImportdomestic(String importdomestic) {
        this.importdomestic = importdomestic == null ? null : importdomestic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.placeorigin
     *
     * @return the value of t_ctr_goods.placeorigin
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getPlaceorigin() {
        return placeorigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.placeorigin
     *
     * @param placeorigin the value for t_ctr_goods.placeorigin
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setPlaceorigin(String placeorigin) {
        this.placeorigin = placeorigin == null ? null : placeorigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.distributionmode
     *
     * @return the value of t_ctr_goods.distributionmode
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getDistributionmode() {
        return distributionmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.distributionmode
     *
     * @param distributionmode the value for t_ctr_goods.distributionmode
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setDistributionmode(String distributionmode) {
        this.distributionmode = distributionmode == null ? null : distributionmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.unitsize
     *
     * @return the value of t_ctr_goods.unitsize
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getUnitsize() {
        return unitsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.unitsize
     *
     * @param unitsize the value for t_ctr_goods.unitsize
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setUnitsize(String unitsize) {
        this.unitsize = unitsize == null ? null : unitsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.productiondate
     *
     * @return the value of t_ctr_goods.productiondate
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getProductiondate() {
        return productiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.productiondate
     *
     * @param productiondate the value for t_ctr_goods.productiondate
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setProductiondate(String productiondate) {
        this.productiondate = productiondate == null ? null : productiondate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.shelflife
     *
     * @return the value of t_ctr_goods.shelflife
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getShelflife() {
        return shelflife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.shelflife
     *
     * @param shelflife the value for t_ctr_goods.shelflife
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setShelflife(String shelflife) {
        this.shelflife = shelflife == null ? null : shelflife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.purchase
     *
     * @return the value of t_ctr_goods.purchase
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getPurchase() {
        return purchase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.purchase
     *
     * @param purchase the value for t_ctr_goods.purchase
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setPurchase(String purchase) {
        this.purchase = purchase == null ? null : purchase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_goods.detailsimgsrc
     *
     * @return the value of t_ctr_goods.detailsimgsrc
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public String getDetailsimgsrc() {
        return detailsimgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_goods.detailsimgsrc
     *
     * @param detailsimgsrc the value for t_ctr_goods.detailsimgsrc
     *
     * @mbggenerated Mon Sep 21 10:22:56 CST 2015
     */
    public void setDetailsimgsrc(String detailsimgsrc) {
        this.detailsimgsrc = detailsimgsrc == null ? null : detailsimgsrc.trim();
    }
}