package com.ssic.shop.manage.pojo;

import java.util.Date;

public class LuckDraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.id
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.prize_name
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.prize_count
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private Integer prizeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.prize_chances
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private Integer prizeChances;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.image_url
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.create_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.last_update_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_lucky_draw.stat
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.id
     *
     * @return the value of t_ctr_lucky_draw.id
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.id
     *
     * @param id the value for t_ctr_lucky_draw.id
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.prize_name
     *
     * @return the value of t_ctr_lucky_draw.prize_name
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.prize_name
     *
     * @param prizeName the value for t_ctr_lucky_draw.prize_name
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.prize_count
     *
     * @return the value of t_ctr_lucky_draw.prize_count
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public Integer getPrizeCount() {
        return prizeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.prize_count
     *
     * @param prizeCount the value for t_ctr_lucky_draw.prize_count
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setPrizeCount(Integer prizeCount) {
        this.prizeCount = prizeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.prize_chances
     *
     * @return the value of t_ctr_lucky_draw.prize_chances
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public Integer getPrizeChances() {
        return prizeChances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.prize_chances
     *
     * @param prizeChances the value for t_ctr_lucky_draw.prize_chances
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setPrizeChances(Integer prizeChances) {
        this.prizeChances = prizeChances;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.image_url
     *
     * @return the value of t_ctr_lucky_draw.image_url
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.image_url
     *
     * @param imageUrl the value for t_ctr_lucky_draw.image_url
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.create_time
     *
     * @return the value of t_ctr_lucky_draw.create_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.create_time
     *
     * @param createTime the value for t_ctr_lucky_draw.create_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.last_update_time
     *
     * @return the value of t_ctr_lucky_draw.last_update_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_lucky_draw.last_update_time
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_lucky_draw.stat
     *
     * @return the value of t_ctr_lucky_draw.stat
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_lucky_draw.stat
     *
     * @param stat the value for t_ctr_lucky_draw.stat
     *
     * @mbggenerated Mon Sep 21 14:36:44 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}