package com.ssic.shop.manage.pojo;

import java.util.Date;

public class WeixnUserCafetorium {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.open_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.cafetorium_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private String cafetoriumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.create_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.last_update_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.is_default
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_weixn_user_cafetorium.stat
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.id
     *
     * @return the value of t_ctr_weixn_user_cafetorium.id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.id
     *
     * @param id the value for t_ctr_weixn_user_cafetorium.id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.open_id
     *
     * @return the value of t_ctr_weixn_user_cafetorium.open_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.open_id
     *
     * @param openId the value for t_ctr_weixn_user_cafetorium.open_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.cafetorium_id
     *
     * @return the value of t_ctr_weixn_user_cafetorium.cafetorium_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public String getCafetoriumId() {
        return cafetoriumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.cafetorium_id
     *
     * @param cafetoriumId the value for t_ctr_weixn_user_cafetorium.cafetorium_id
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setCafetoriumId(String cafetoriumId) {
        this.cafetoriumId = cafetoriumId == null ? null : cafetoriumId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.create_time
     *
     * @return the value of t_ctr_weixn_user_cafetorium.create_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.create_time
     *
     * @param createTime the value for t_ctr_weixn_user_cafetorium.create_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.last_update_time
     *
     * @return the value of t_ctr_weixn_user_cafetorium.last_update_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_weixn_user_cafetorium.last_update_time
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.is_default
     *
     * @return the value of t_ctr_weixn_user_cafetorium.is_default
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.is_default
     *
     * @param isDefault the value for t_ctr_weixn_user_cafetorium.is_default
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_weixn_user_cafetorium.stat
     *
     * @return the value of t_ctr_weixn_user_cafetorium.stat
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_weixn_user_cafetorium.stat
     *
     * @param stat the value for t_ctr_weixn_user_cafetorium.stat
     *
     * @mbggenerated Thu Oct 29 17:54:20 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}