package com.ssic.catering.base.dto;

import java.io.Serializable;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**		
 * <p>Title: NextWeekCarteDto </p>
 * <p>Description: 类描述</p>
 * <p>Copyright (c) 2015 </p>
 * <p>Company: 上海天坊信息科技有限公司</p>
 * @author yuanbin	
 * @date 2015年8月5日 下午1:07:27	
 * @version 1.0
 * <p>修改人：yuanbin</p>
 * <p>修改时间：2015年8月5日 下午1:07:27</p>
 * <p>修改备注：</p>
 */
@ToString
public class NextWeekCarteDtos implements Serializable
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_next_week_carte.id
     *
     * @mbggenerated Wed Aug 05 09:57:48 CST 2015
     */
    @Getter
    @Setter
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_next_week_carte.dish_name
     *
     * @mbggenerated Wed Aug 05 09:57:48 CST 2015
     */
    @Getter
    @Setter
    private String dishName;

    @Getter
    @Setter
    private int count;

    @Getter
    @Setter
    private int countDishName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_next_week_carte.crate_type_id
     *
     * @mbggenerated Wed Aug 05 09:57:48 CST 2015
     */
    @Getter
    @Setter
    private String carteTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_next_week_carte.carte_week
     *
     * @mbggenerated Wed Aug 05 09:57:48 CST 2015
     */
    @Getter
    @Setter
    private String carteWeek;

    @Getter
    @Setter
    private String carteWeekDesc;
    /**
     * 每个食堂的菜单标题时间
     */
    @Getter
    @Setter
    private Date carteTime;
    /**
     * 食堂ID
     */
    @Getter
    @Setter
    private String cafetoriumId;

}
