package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.AdminMenu;
import com.ssic.catering.base.pojo.AdminMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int countByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insert(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insertSelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    List<AdminMenu> selectByExample(AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    AdminMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdminMenu record, @Param("example") AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExample(@Param("record") AdminMenu record, @Param("example") AdminMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKeySelective(AdminMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKey(AdminMenu record);
}