package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.AdminRoleMenu;
import com.ssic.catering.base.pojo.AdminRoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int countByExample(AdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByExample(AdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insert(AdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insertSelective(AdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    List<AdminRoleMenu> selectByExample(AdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    AdminRoleMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") AdminRoleMenu record, @Param("example") AdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExample(@Param("record") AdminRoleMenu record, @Param("example") AdminRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKeySelective(AdminRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_admin_role_menu
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKey(AdminRoleMenu record);
}