package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.CarteType;
import com.ssic.catering.base.pojo.CarteTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarteTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int countByExample(CarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int deleteByExample(CarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int insert(CarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int insertSelective(CarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    List<CarteType> selectByExample(CarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    CarteType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int updateByExampleSelective(@Param("record") CarteType record, @Param("example") CarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int updateByExample(@Param("record") CarteType record, @Param("example") CarteTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int updateByPrimaryKeySelective(CarteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_carte_type
     *
     * @mbggenerated Tue Sep 22 10:32:06 CST 2015
     */
    int updateByPrimaryKey(CarteType record);
}