package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.CommentSensitive;
import com.ssic.catering.base.pojo.CommentSensitiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentSensitiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int countByExample(CommentSensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int deleteByExample(CommentSensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int insert(CommentSensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int insertSelective(CommentSensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    List<CommentSensitive> selectByExample(CommentSensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    CommentSensitive selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int updateByExampleSelective(@Param("record") CommentSensitive record, @Param("example") CommentSensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int updateByExample(@Param("record") CommentSensitive record, @Param("example") CommentSensitiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int updateByPrimaryKeySelective(CommentSensitive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_comment_sensitive
     *
     * @mbggenerated Thu Aug 06 13:04:52 CST 2015
     */
    int updateByPrimaryKey(CommentSensitive record);
}