package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.ConfigList;
import com.ssic.catering.base.pojo.ConfigListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int countByExample(ConfigListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByExample(ConfigListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insert(ConfigList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insertSelective(ConfigList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    List<ConfigList> selectByExample(ConfigListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    ConfigList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") ConfigList record, @Param("example") ConfigListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExample(@Param("record") ConfigList record, @Param("example") ConfigListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKeySelective(ConfigList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_list
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKey(ConfigList record);
}