package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.Config;
import com.ssic.catering.base.pojo.ConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int countByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int deleteByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    List<Config> selectByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    Config selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int updateByExample(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config
     *
     * @mbggenerated Tue Nov 03 11:09:35 CST 2015
     */
    int updateByPrimaryKey(Config record);
}