package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.ConfigScoreValveConf;
import com.ssic.catering.base.pojo.ConfigScoreValveConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigScoreValveConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int countByExample(ConfigScoreValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int deleteByExample(ConfigScoreValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int insert(ConfigScoreValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int insertSelective(ConfigScoreValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    List<ConfigScoreValveConf> selectByExample(ConfigScoreValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    ConfigScoreValveConf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int updateByExampleSelective(@Param("record") ConfigScoreValveConf record, @Param("example") ConfigScoreValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int updateByExample(@Param("record") ConfigScoreValveConf record, @Param("example") ConfigScoreValveConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int updateByPrimaryKeySelective(ConfigScoreValveConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_config_score_valve_conf
     *
     * @mbggenerated Mon Aug 10 14:43:29 CST 2015
     */
    int updateByPrimaryKey(ConfigScoreValveConf record);
}