package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.GroupInfo;
import com.ssic.catering.base.pojo.GroupInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int countByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int deleteByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int insert(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int insertSelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    List<GroupInfo> selectByExample(GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    GroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int updateByExampleSelective(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int updateByExample(@Param("record") GroupInfo record, @Param("example") GroupInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int updateByPrimaryKeySelective(GroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_group_info
     *
     * @mbggenerated Tue Oct 20 14:10:00 CST 2015
     */
    int updateByPrimaryKey(GroupInfo record);
}