package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.News;
import com.ssic.catering.base.pojo.NewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    List<News> selectByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    News selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news
     *
     * @mbggenerated Fri Oct 23 14:24:59 CST 2015
     */
    int updateByPrimaryKey(News record);
}