package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.NewsImage;
import com.ssic.catering.base.pojo.NewsImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int countByExample(NewsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByExample(NewsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insert(NewsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int insertSelective(NewsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    List<NewsImage> selectByExample(NewsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    NewsImage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") NewsImage record, @Param("example") NewsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByExample(@Param("record") NewsImage record, @Param("example") NewsImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKeySelective(NewsImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_news_image
     *
     * @mbggenerated Tue Aug 04 14:59:20 CST 2015
     */
    int updateByPrimaryKey(NewsImage record);
}