package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.Notify;
import com.ssic.catering.base.pojo.NotifyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int countByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int deleteByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    List<Notify> selectByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    Notify selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_notify
     *
     * @mbggenerated Fri Oct 23 14:31:30 CST 2015
     */
    int updateByPrimaryKey(Notify record);
}