package com.ssic.catering.base.mapper;

import com.ssic.catering.base.pojo.SensitiveWarningReport;
import com.ssic.catering.base.pojo.SensitiveWarningReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SensitiveWarningReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int countByExample(SensitiveWarningReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int deleteByExample(SensitiveWarningReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int insert(SensitiveWarningReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int insertSelective(SensitiveWarningReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    List<SensitiveWarningReport> selectByExample(SensitiveWarningReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    SensitiveWarningReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int updateByExampleSelective(@Param("record") SensitiveWarningReport record, @Param("example") SensitiveWarningReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int updateByExample(@Param("record") SensitiveWarningReport record, @Param("example") SensitiveWarningReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int updateByPrimaryKeySelective(SensitiveWarningReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ctr_sensitive_warning_report
     *
     * @mbggenerated Wed Aug 12 09:43:39 CST 2015
     */
    int updateByPrimaryKey(SensitiveWarningReport record);
}