package com.ssic.game.common.pojo;

import java.util.Date;

public class Actions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.proc_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.next_task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String nextTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.type
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.action_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String actionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_actions.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.id
     *
     * @return the value of t_ims_actions.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.id
     *
     * @param id the value for t_ims_actions.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.name
     *
     * @return the value of t_ims_actions.name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.name
     *
     * @param name the value for t_ims_actions.name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.proj_id
     *
     * @return the value of t_ims_actions.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.proj_id
     *
     * @param projId the value for t_ims_actions.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.proc_id
     *
     * @return the value of t_ims_actions.proc_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.proc_id
     *
     * @param procId the value for t_ims_actions.proc_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.task_id
     *
     * @return the value of t_ims_actions.task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.task_id
     *
     * @param taskId the value for t_ims_actions.task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.next_task_id
     *
     * @return the value of t_ims_actions.next_task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getNextTaskId() {
        return nextTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.next_task_id
     *
     * @param nextTaskId the value for t_ims_actions.next_task_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setNextTaskId(String nextTaskId) {
        this.nextTaskId = nextTaskId == null ? null : nextTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.type
     *
     * @return the value of t_ims_actions.type
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.type
     *
     * @param type the value for t_ims_actions.type
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.action_url
     *
     * @return the value of t_ims_actions.action_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.action_url
     *
     * @param actionUrl the value for t_ims_actions.action_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl == null ? null : actionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.stat
     *
     * @return the value of t_ims_actions.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.stat
     *
     * @param stat the value for t_ims_actions.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.last_update_time
     *
     * @return the value of t_ims_actions.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_actions.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_actions.create_time
     *
     * @return the value of t_ims_actions.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_actions.create_time
     *
     * @param createTime the value for t_ims_actions.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}