package com.ssic.game.common.pojo;

import java.util.Date;

public class DeptUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.proj_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.dept_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.user_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.stat
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.last_update_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.create_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_dept_users.is_admin
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    private String isAdmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.id
     *
     * @return the value of t_ims_dept_users.id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.id
     *
     * @param id the value for t_ims_dept_users.id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.proj_id
     *
     * @return the value of t_ims_dept_users.proj_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.proj_id
     *
     * @param projId the value for t_ims_dept_users.proj_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.dept_id
     *
     * @return the value of t_ims_dept_users.dept_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.dept_id
     *
     * @param deptId the value for t_ims_dept_users.dept_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.user_id
     *
     * @return the value of t_ims_dept_users.user_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.user_id
     *
     * @param userId the value for t_ims_dept_users.user_id
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.stat
     *
     * @return the value of t_ims_dept_users.stat
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.stat
     *
     * @param stat the value for t_ims_dept_users.stat
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.last_update_time
     *
     * @return the value of t_ims_dept_users.last_update_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_dept_users.last_update_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.create_time
     *
     * @return the value of t_ims_dept_users.create_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.create_time
     *
     * @param createTime the value for t_ims_dept_users.create_time
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_dept_users.is_admin
     *
     * @return the value of t_ims_dept_users.is_admin
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_dept_users.is_admin
     *
     * @param isAdmin the value for t_ims_dept_users.is_admin
     *
     * @mbggenerated Tue Jul 21 18:12:00 CST 2015
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin == null ? null : isAdmin.trim();
    }
}