package com.ssic.game.common.pojo;

import java.util.Date;

public class FieldsTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.proj_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.order_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.param_desc
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String paramDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.param_name
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.pattern
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String pattern;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.is_encrypt
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Boolean isEncrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.is_uniline
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Boolean isUniline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.is_diy
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Boolean isDiy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.length
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.height
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.data_type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.is_need
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Boolean isNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.is_clone
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Boolean isClone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.stat
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.last_update_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.create_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.proc_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_fields_template.form_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    private String formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.id
     *
     * @return the value of t_ims_fields_template.id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.id
     *
     * @param id the value for t_ims_fields_template.id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.proj_id
     *
     * @return the value of t_ims_fields_template.proj_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.proj_id
     *
     * @param projId the value for t_ims_fields_template.proj_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.order_id
     *
     * @return the value of t_ims_fields_template.order_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.order_id
     *
     * @param orderId the value for t_ims_fields_template.order_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.param_desc
     *
     * @return the value of t_ims_fields_template.param_desc
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.param_desc
     *
     * @param paramDesc the value for t_ims_fields_template.param_desc
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.param_name
     *
     * @return the value of t_ims_fields_template.param_name
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.param_name
     *
     * @param paramName the value for t_ims_fields_template.param_name
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.pattern
     *
     * @return the value of t_ims_fields_template.pattern
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.pattern
     *
     * @param pattern the value for t_ims_fields_template.pattern
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setPattern(String pattern) {
        this.pattern = pattern == null ? null : pattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.is_encrypt
     *
     * @return the value of t_ims_fields_template.is_encrypt
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Boolean getIsEncrypt() {
        return isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.is_encrypt
     *
     * @param isEncrypt the value for t_ims_fields_template.is_encrypt
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setIsEncrypt(Boolean isEncrypt) {
        this.isEncrypt = isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.is_uniline
     *
     * @return the value of t_ims_fields_template.is_uniline
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Boolean getIsUniline() {
        return isUniline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.is_uniline
     *
     * @param isUniline the value for t_ims_fields_template.is_uniline
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setIsUniline(Boolean isUniline) {
        this.isUniline = isUniline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.is_diy
     *
     * @return the value of t_ims_fields_template.is_diy
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Boolean getIsDiy() {
        return isDiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.is_diy
     *
     * @param isDiy the value for t_ims_fields_template.is_diy
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setIsDiy(Boolean isDiy) {
        this.isDiy = isDiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.length
     *
     * @return the value of t_ims_fields_template.length
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.length
     *
     * @param length the value for t_ims_fields_template.length
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.height
     *
     * @return the value of t_ims_fields_template.height
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.height
     *
     * @param height the value for t_ims_fields_template.height
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.type
     *
     * @return the value of t_ims_fields_template.type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.type
     *
     * @param type the value for t_ims_fields_template.type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.data_type
     *
     * @return the value of t_ims_fields_template.data_type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.data_type
     *
     * @param dataType the value for t_ims_fields_template.data_type
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.is_need
     *
     * @return the value of t_ims_fields_template.is_need
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Boolean getIsNeed() {
        return isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.is_need
     *
     * @param isNeed the value for t_ims_fields_template.is_need
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setIsNeed(Boolean isNeed) {
        this.isNeed = isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.is_clone
     *
     * @return the value of t_ims_fields_template.is_clone
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Boolean getIsClone() {
        return isClone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.is_clone
     *
     * @param isClone the value for t_ims_fields_template.is_clone
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setIsClone(Boolean isClone) {
        this.isClone = isClone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.stat
     *
     * @return the value of t_ims_fields_template.stat
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.stat
     *
     * @param stat the value for t_ims_fields_template.stat
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.last_update_time
     *
     * @return the value of t_ims_fields_template.last_update_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_fields_template.last_update_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.create_time
     *
     * @return the value of t_ims_fields_template.create_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.create_time
     *
     * @param createTime the value for t_ims_fields_template.create_time
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.proc_id
     *
     * @return the value of t_ims_fields_template.proc_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.proc_id
     *
     * @param procId the value for t_ims_fields_template.proc_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_fields_template.form_id
     *
     * @return the value of t_ims_fields_template.form_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_fields_template.form_id
     *
     * @param formId the value for t_ims_fields_template.form_id
     *
     * @mbggenerated Sat Jun 27 14:44:45 CST 2015
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }
}