package com.ssic.game.common.pojo;

import java.util.Date;

public class ImsQueryAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.project_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.query_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private String queryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.name
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.url
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.stat
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.last_update_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_query_action.create_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.id
     *
     * @return the value of t_ims_query_action.id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.id
     *
     * @param id the value for t_ims_query_action.id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.project_id
     *
     * @return the value of t_ims_query_action.project_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.project_id
     *
     * @param projectId the value for t_ims_query_action.project_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.query_id
     *
     * @return the value of t_ims_query_action.query_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public String getQueryId() {
        return queryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.query_id
     *
     * @param queryId the value for t_ims_query_action.query_id
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setQueryId(String queryId) {
        this.queryId = queryId == null ? null : queryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.name
     *
     * @return the value of t_ims_query_action.name
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.name
     *
     * @param name the value for t_ims_query_action.name
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.url
     *
     * @return the value of t_ims_query_action.url
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.url
     *
     * @param url the value for t_ims_query_action.url
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.stat
     *
     * @return the value of t_ims_query_action.stat
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.stat
     *
     * @param stat the value for t_ims_query_action.stat
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.last_update_time
     *
     * @return the value of t_ims_query_action.last_update_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_query_action.last_update_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_query_action.create_time
     *
     * @return the value of t_ims_query_action.create_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_query_action.create_time
     *
     * @param createTime the value for t_ims_query_action.create_time
     *
     * @mbggenerated Tue Jul 28 16:09:32 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}