package com.ssic.game.common.pojo;

import java.util.Date;

public class Menu {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.name
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.remark
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.url
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.pid
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.stat
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.create_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.last_update_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.menu_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.proj_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.proc_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_menu.proc_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    private Integer procType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.id
     *
     * @return the value of t_ims_menu.id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.id
     *
     * @param id the value for t_ims_menu.id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.name
     *
     * @return the value of t_ims_menu.name
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.name
     *
     * @param name the value for t_ims_menu.name
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.remark
     *
     * @return the value of t_ims_menu.remark
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.remark
     *
     * @param remark the value for t_ims_menu.remark
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.url
     *
     * @return the value of t_ims_menu.url
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.url
     *
     * @param url the value for t_ims_menu.url
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.pid
     *
     * @return the value of t_ims_menu.pid
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.pid
     *
     * @param pid the value for t_ims_menu.pid
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.stat
     *
     * @return the value of t_ims_menu.stat
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.stat
     *
     * @param stat the value for t_ims_menu.stat
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.create_time
     *
     * @return the value of t_ims_menu.create_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.create_time
     *
     * @param createTime the value for t_ims_menu.create_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.last_update_time
     *
     * @return the value of t_ims_menu.last_update_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_menu.last_update_time
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.menu_type
     *
     * @return the value of t_ims_menu.menu_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.menu_type
     *
     * @param menuType the value for t_ims_menu.menu_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.proj_id
     *
     * @return the value of t_ims_menu.proj_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.proj_id
     *
     * @param projId the value for t_ims_menu.proj_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.proc_id
     *
     * @return the value of t_ims_menu.proc_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.proc_id
     *
     * @param procId the value for t_ims_menu.proc_id
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_menu.proc_type
     *
     * @return the value of t_ims_menu.proc_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public Integer getProcType() {
        return procType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_menu.proc_type
     *
     * @param procType the value for t_ims_menu.proc_type
     *
     * @mbggenerated Wed Aug 12 11:46:49 CST 2015
     */
    public void setProcType(Integer procType) {
        this.procType = procType;
    }
}