package com.ssic.game.common.pojo;

import java.util.Date;

public class ParamConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.param_name
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private String paramName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.param_value
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.param_describe
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private String paramDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.create_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.stat
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.param_type
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private Integer paramType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ctr_param_config.proj_id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    private String projId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.id
     *
     * @return the value of t_ctr_param_config.id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.id
     *
     * @param id the value for t_ctr_param_config.id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.param_name
     *
     * @return the value of t_ctr_param_config.param_name
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.param_name
     *
     * @param paramName the value for t_ctr_param_config.param_name
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setParamName(String paramName) {
        this.paramName = paramName == null ? null : paramName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.param_value
     *
     * @return the value of t_ctr_param_config.param_value
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.param_value
     *
     * @param paramValue the value for t_ctr_param_config.param_value
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.param_describe
     *
     * @return the value of t_ctr_param_config.param_describe
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public String getParamDescribe() {
        return paramDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.param_describe
     *
     * @param paramDescribe the value for t_ctr_param_config.param_describe
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setParamDescribe(String paramDescribe) {
        this.paramDescribe = paramDescribe == null ? null : paramDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.create_time
     *
     * @return the value of t_ctr_param_config.create_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.create_time
     *
     * @param createTime the value for t_ctr_param_config.create_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.last_update_time
     *
     * @return the value of t_ctr_param_config.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.last_update_time
     *
     * @param lastUpdateTime the value for t_ctr_param_config.last_update_time
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.stat
     *
     * @return the value of t_ctr_param_config.stat
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.stat
     *
     * @param stat the value for t_ctr_param_config.stat
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.param_type
     *
     * @return the value of t_ctr_param_config.param_type
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public Integer getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.param_type
     *
     * @param paramType the value for t_ctr_param_config.param_type
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setParamType(Integer paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ctr_param_config.proj_id
     *
     * @return the value of t_ctr_param_config.proj_id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ctr_param_config.proj_id
     *
     * @param projId the value for t_ctr_param_config.proj_id
     *
     * @mbggenerated Tue Oct 20 14:44:56 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }
}