package com.ssic.game.common.pojo;

import java.util.Date;

public class Process {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.proc_name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String procName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.img_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.describes
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String describes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.isDefine
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Integer isdefine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.start_task
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private String startTask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.start_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.end_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.state
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.id
     *
     * @return the value of t_ims_process.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.id
     *
     * @param id the value for t_ims_process.id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.proj_id
     *
     * @return the value of t_ims_process.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.proj_id
     *
     * @param projId the value for t_ims_process.proj_id
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.proc_name
     *
     * @return the value of t_ims_process.proc_name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getProcName() {
        return procName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.proc_name
     *
     * @param procName the value for t_ims_process.proc_name
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.img_url
     *
     * @return the value of t_ims_process.img_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.img_url
     *
     * @param imgUrl the value for t_ims_process.img_url
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.describes
     *
     * @return the value of t_ims_process.describes
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public String getDescribes() {
        return describes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.describes
     *
     * @param describes the value for t_ims_process.describes
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setDescribes(String describes) {
        this.describes = describes == null ? null : describes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.isDefine
     *
     * @return the value of t_ims_process.isDefine
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Integer getIsdefine() {
        return isdefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.isDefine
     *
     * @param isdefine the value for t_ims_process.isDefine
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setIsdefine(Integer isdefine) {
        this.isdefine = isdefine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.start_task
     *
     * @return the value of t_ims_process.start_task
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.stat
     *
     * @return the value of t_ims_process.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    public String getStartTask() {
		return startTask;
	}

	public void setStartTask(String startTask) {
		this.startTask = startTask;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.stat
     *
     * @param stat the value for t_ims_process.stat
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.start_date
     *
     * @return the value of t_ims_process.start_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.start_date
     *
     * @param startDate the value for t_ims_process.start_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.end_date
     *
     * @return the value of t_ims_process.end_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.end_date
     *
     * @param endDate the value for t_ims_process.end_date
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.state
     *
     * @return the value of t_ims_process.state
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.state
     *
     * @param state the value for t_ims_process.state
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.last_update_time
     *
     * @return the value of t_ims_process.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_process.last_update_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process.create_time
     *
     * @return the value of t_ims_process.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process.create_time
     *
     * @param createTime the value for t_ims_process.create_time
     *
     * @mbggenerated Fri Jun 26 21:19:17 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}