package com.ssic.game.common.pojo;

import java.util.Date;

public class ProcInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.proj_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String projId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.proc_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.proc_name
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String procName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.now_task_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String nowTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.stat
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.retire_date
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private Date retireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.owner
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.last_update_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.create_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_proc_instance.state
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.id
     *
     * @return the value of t_ims_proc_instance.id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.id
     *
     * @param id the value for t_ims_proc_instance.id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.proj_id
     *
     * @return the value of t_ims_proc_instance.proj_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getProjId() {
        return projId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.proj_id
     *
     * @param projId the value for t_ims_proc_instance.proj_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setProjId(String projId) {
        this.projId = projId == null ? null : projId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.proc_id
     *
     * @return the value of t_ims_proc_instance.proc_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.proc_id
     *
     * @param procId the value for t_ims_proc_instance.proc_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.proc_name
     *
     * @return the value of t_ims_proc_instance.proc_name
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getProcName() {
        return procName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.proc_name
     *
     * @param procName the value for t_ims_proc_instance.proc_name
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setProcName(String procName) {
        this.procName = procName == null ? null : procName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.now_task_id
     *
     * @return the value of t_ims_proc_instance.now_task_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getNowTaskId() {
        return nowTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.now_task_id
     *
     * @param nowTaskId the value for t_ims_proc_instance.now_task_id
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setNowTaskId(String nowTaskId) {
        this.nowTaskId = nowTaskId == null ? null : nowTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.stat
     *
     * @return the value of t_ims_proc_instance.stat
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.stat
     *
     * @param stat the value for t_ims_proc_instance.stat
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.retire_date
     *
     * @return the value of t_ims_proc_instance.retire_date
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public Date getRetireDate() {
        return retireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.retire_date
     *
     * @param retireDate the value for t_ims_proc_instance.retire_date
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setRetireDate(Date retireDate) {
        this.retireDate = retireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.owner
     *
     * @return the value of t_ims_proc_instance.owner
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.owner
     *
     * @param owner the value for t_ims_proc_instance.owner
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.last_update_time
     *
     * @return the value of t_ims_proc_instance.last_update_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.last_update_time
     *
     * @param lastUpdateTime the value for t_ims_proc_instance.last_update_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.create_time
     *
     * @return the value of t_ims_proc_instance.create_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.create_time
     *
     * @param createTime the value for t_ims_proc_instance.create_time
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_proc_instance.state
     *
     * @return the value of t_ims_proc_instance.state
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_proc_instance.state
     *
     * @param state the value for t_ims_proc_instance.state
     *
     * @mbggenerated Tue Aug 04 10:27:53 CST 2015
     */
    public void setState(Integer state) {
        this.state = state;
    }
}