package com.ssic.game.common.pojo;

import java.util.Date;

public class ProcessRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.proc_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private String procId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.role_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.stat
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private Integer stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.last_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ims_process_role.create_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.id
     *
     * @return the value of t_ims_process_role.id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.id
     *
     * @param id the value for t_ims_process_role.id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.proc_id
     *
     * @return the value of t_ims_process_role.proc_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public String getProcId() {
        return procId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.proc_id
     *
     * @param procId the value for t_ims_process_role.proc_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setProcId(String procId) {
        this.procId = procId == null ? null : procId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.role_id
     *
     * @return the value of t_ims_process_role.role_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.role_id
     *
     * @param roleId the value for t_ims_process_role.role_id
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.stat
     *
     * @return the value of t_ims_process_role.stat
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.stat
     *
     * @param stat the value for t_ims_process_role.stat
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.last_time
     *
     * @return the value of t_ims_process_role.last_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.last_time
     *
     * @param lastTime the value for t_ims_process_role.last_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ims_process_role.create_time
     *
     * @return the value of t_ims_process_role.create_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ims_process_role.create_time
     *
     * @param createTime the value for t_ims_process_role.create_time
     *
     * @mbggenerated Fri Jun 26 18:52:38 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}